generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: linkerd.io
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 30 15:31:59 2026 GMT
  hsts: false
- host: kubernetes.default.svc
  https: false
- host: metrics-api.linkerd-viz.svc.cluster.local
  https: false
domains:
- domain: linkerd.io
  dnssec: false
  caa: []
  spf: false
  dmarc: false
- domain: default.svc
  dnssec: false
  caa: []
  spf: false
  dmarc: false
